# windows rule file of hyprland, should be sourced in hyprland.conf

# Example windowrule v1
# windowrule = float, ^(kitty)$
# Example windowrule 
# windowrule = float,class:^(kitty)$,title:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# windowrule = suppressevent maximize, class:.* # You'll probably like this.

# floating file explorer
windowrule = match:class ^nemo$, float on, size monitor_w*0.5 monitor_h*0.5, center on
# ueberzugpp image preview
windowrule = match:class ^ueberzugpp_.*$, float on, no_initial_focus on, opacity 1 override
# qemu
windowrule = match:class ^qemu$, float on, opacity 1 override
# virtmanager
windowrule = match:class ^virt-manager$, opacity 1 override
# pavucontrol things
windowrule = match:class ^org.pulseaudio.pavucontrol$, float on, size monitor_w*0.5 monitor_h*0.5, center on
# network
windowrule = match:class ^nm-connection-editor$, float on
# obs
windowrule = match:class ^com.obsproject.Studio$, opacity 1 override
# remote desktop
windowrule = match:class ^org.remmina.Remmina$, float on
# unity editor
windowrule = match:class ^unityhub$, opacity 1 override
# gimp
windowrule = match:class gimp, opacity 1 override
# blender
windowrule = match:class ^blender$, opacity 1 override
# darktable
windowrule = match:class ^(Darktable)$, opacity 1 override
# eden
windowrule = match:class ^eden$, opacity 1 override
# godot
windowrule = match:class ^org.godotengine.Editor$, opacity 1 override
# chill with you
windowrule {
    name = chill-with-you
    match:class = steam_app_3548580
    opacity = 1 override
    # float = on
    # pin = on
    rounding = 0
}
