[mgr]
append_keymap = [
    { on = [ "g", "D" ], run = 'cd ~/Documents/', desc = "Go to the documents directory" },
    { on = [ "g", "C" ], run = 'cd ~/Documents/course', desc = "Go to the course directory" },
]

