#! /usr/bin/sh

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-${HOME}/.local/state}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-${HOME}/.cache}"
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"


# history
HISTFILE="$XDG_STATE_HOME/history"
HISTSIZE=1000
# gnu readline
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc
# android toolchain
export ANDROID_USER_HOME="$XDG_DATA_HOME"/android
alias adb='HOME="$XDG_DATA_HOME"/android adb'
# nv
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
# gnupg
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
# node
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export NODE_REPL_HISTORY="$XDG_STATE_HOME"/node_repl_history
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME"/npm
export NPM_CONFIG_TMP="$XDG_RUNTIME_DIR"/npm
# rust toolchain
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
# dotnet toolchain
export DOTNET_CLI_HOME="$XDG_DATA_HOME"/dotnet
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
# java toolchain
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
# python toolchain
export PYTHON_HISTORY="$XDG_STATE_HOME"/python
