#!/bin/sh

# basic shell config


# enable color support
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    export LS_COLORS="$LS_COLORS:ow=30;44:" # fix ls color for folders with 777 permissions

    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias diff='diff --color=auto'
    alias ip='ip --color=auto'
fi

# enable color support of manpage
export MANROFFOPT=-c
export LESS=-R
export LESS_TERMCAP_mb=$'\E[1;31m'     # begin blink
export LESS_TERMCAP_md=$'\E[1;36m'     # begin bold
export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
export LESS_TERMCAP_so=$'\E[01;33m'    # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
export LESS_TERMCAP_ue=$'\E[0m'        # reset underline

# history setting
HISTFILE="${XDG_STATE_HOME:-${HOME}/.local/state}/history"
HISTSIZE=1000

# ---------------------- OTHERS ---------------------

# ---------------- functions ----------------

# yazi wrapper
if command -v yazi 2>&1 > /dev/null; then
    function yazi_wrapper() {
        local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
        yazi "$@" --cwd-file="$tmp"
        if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
            cd -- "$cwd"
        fi
        rm -f -- "$tmp"
    }
fi

if command -v zellij 2>&1 > /dev/null; then
    function zellij_wrapper() {
        zellij "$@"
        # remove all the temp cache
        find "${XDG_CACHE_HOME:-$HOME/.cache}/zellij" \
            -maxdepth 1 -type d \
            -name "????????-????-????-????-????????????" \
            -exec rm -rf {} +
    }
fi

# set the proxy
# setproxy() {
#     local proxy_server="localhost"
#     local socks5_port="20170"
#     local http_port="20171"
#     local http_rule_port="20172"
#     if [ "$1" = "http" ]; then
#         export http_proxy="http://${proxy_server}:${http_port}"
#         export https_proxy="http://${proxy_server}:${http_port}"
#         echo "HTTP proxy is set."
#     elif [ "$1" = "socks5" ]; then
#         export SOCKS5_PROXY="${proxy_server}:${socks5_port}"
#         echo "SOCKS5 proxy is set."
#     elif [ "$1" = "all" ] || [ "$1" = "on" ]; then
#         export http_proxy="http://${proxy_server}:${http_rule_port}"
#         export https_proxy="http://${proxy_server}:${http_rule_port}"
#         export SOCKS5_PROXY="${proxy_server}:${socks5_port}"
#         echo "ALL_PROXY is set."
#     elif [ "$1" = "off" ]; then
#         unset http_proxy
#         unset https_proxy
#         unset SOCKS5_PROXY
#         echo "Proxy settings are unset."
#     else
#         echo "Usage: set_proxy on|all|http|socks5|off"
#     fi
#     # check the proxy
#     echo "\nnow:"
#     curl cip.cc
# }

passgen() {
    read -s MSG
    echo -n "$MSG" | openssl dgst -sha256 -binary | base64 | head -c 12 | awk '{print $0"K@!"}'
}

cheat() {
    curl -s "cheat.sh/$1" | {
        if command -v bat 2>&1 > /dev/null; then
            bat -p
        else
            less
        fi
    }
}

claudman() {
    local config=${XDG_CONFIG_HOME:-${HOME}/.config}/claude
    local cache=${XDG_CACHE_HOME:-${HOME}/.cache}/claude
    local state=${XDG_STATE_HOME:-${HOME}/.local/state}/.claude.json
    [ -d $config ] || mkdir -p $config
    [ -d $cache ] || mkdir -p $cache
    [ -f $state ] || touch $state

    podman run -it --rm \
        --name claude --hostname claude \
        -v .:/root/workspace \
        -v $state:/root/.claude.json \
        -v $config:/root/.claude \
        -v $cache:/root/.cache/claude \
        localhost/claude:latest
}

# ---------------- constants ----------------

# some aliases
alias v='nvim'
alias f='fastfetch'
alias y='yazi_wrapper'
alias z='zellij_wrapper'

# env
command -v nvim > /dev/null 2>&1 && export EDITOR='nvim'
command -v bat > /dev/null 2>&1 && export PAGER="bat -p"


if [ -x /usr/bin/micromamba ]; then
    # >>> mamba initialize >>>
    # !! Contents within this block are managed by 'micromamba shell init' !!
    # tweaked to this
    export MAMBA_EXE='/usr/bin/micromamba';
    export MAMBA_ROOT_PREFIX="$HOME/.local/share/mamba";
    __mamba_setup="$("$MAMBA_EXE" shell hook --shell $(basename "$SHELL") --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__mamba_setup"
    else
        alias micromamba="$MAMBA_EXE"  # Fallback on help from micromamba activate
    fi
    alias conda='micromamba'
    unset __mamba_setup
    # <<< mamba initialize <<<
fi


# ---------------- misc ----------------

__get_prompt_extra_info() {
    echo $(__get_conda_env)$(__get_nix_shell)
}

__get_nix_shell() {
    if [ -n "$IN_NIX_SHELL" ]; then
        echo "─{:${name}}"
    fi
}

__get_conda_env() {
    CONDA_SYMBOL=":"
    CONDA_ENV=""
    if [ -n "$CONDA_PREFIX" ]; then
        CONDA_DIR=$(basename $CONDA_PREFIX)
        if [ "$CONDA_DIR" == "anaconda" ]; then
            CONDA_ENV="base"
        else
            CONDA_ENV=$CONDA_DIR
        fi
        echo "─{${CONDA_SYMBOL}${CONDA_ENV}}"
    fi
}
