#!/bin/bash

# Some basic configurations such as
# alias, colors, functions and others
# should be sourced in whichever .xxshrc file


# ---------------------- ALIAS and COLOR ---------------------

# enable color support of ls, less and man, and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    export LS_COLORS="$LS_COLORS:ow=30;44:" # fix ls color for folders with 777 permissions

    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
    alias diff='diff --color=auto'
    alias ip='ip --color=auto'
fi

# enable color support of manpage
# if there is bat, then use bat
if [ -x /usr/bin/bat ]; then
    export MANPAGER="sh -c 'awk '\''{ gsub(/\x1B\[[0-9;]*m/, \"\", \$0); gsub(/.\x08/, \"\", \$0); print }'\'' | bat -p -lman'"
else
    export MANROFFOPT=-c
    export LESS=-R
    export LESS_TERMCAP_mb=$'\E[1;31m'     # begin blink
    export LESS_TERMCAP_md=$'\E[1;36m'     # begin bold
    export LESS_TERMCAP_me=$'\E[0m'        # reset bold/blink
    export LESS_TERMCAP_so=$'\E[01;33m'    # begin reverse video
    export LESS_TERMCAP_se=$'\E[0m'        # reset reverse video
    export LESS_TERMCAP_us=$'\E[1;32m'     # begin underline
    export LESS_TERMCAP_ue=$'\E[0m'        # reset underline
fi

# ---------------------- OTHERS ---------------------

# ---------------- functions ----------------

# yazi wrapper
function yazi_wrapper() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}
alias y='yazi_wrapper'

function zellij_wrapper() {
    zellij "$@"
    # remove all the temp cache
    find "${XDG_CACHE_HOME:-$HOME/.cache}/zellij" \
        -maxdepth 1 -type d \
        -name "????????-????-????-????-????????????" \
        -exec rm -rf {} +
}
alias z='zellij_wrapper'

# set the proxy
# setproxy() {
#     local proxy_server="localhost"
#     local socks5_port="20170"
#     local http_port="20171"
#     local http_rule_port="20172"
#     if [ "$1" = "http" ]; then
#         export http_proxy="http://${proxy_server}:${http_port}"
#         export https_proxy="http://${proxy_server}:${http_port}"
#         echo "HTTP proxy is set."
#     elif [ "$1" = "socks5" ]; then
#         export SOCKS5_PROXY="${proxy_server}:${socks5_port}"
#         echo "SOCKS5 proxy is set."
#     elif [ "$1" = "all" ] || [ "$1" = "on" ]; then
#         export http_proxy="http://${proxy_server}:${http_rule_port}"
#         export https_proxy="http://${proxy_server}:${http_rule_port}"
#         export SOCKS5_PROXY="${proxy_server}:${socks5_port}"
#         echo "ALL_PROXY is set."
#     elif [ "$1" = "off" ]; then
#         unset http_proxy
#         unset https_proxy
#         unset SOCKS5_PROXY
#         echo "Proxy settings are unset."
#     else
#         echo "Usage: set_proxy on|all|http|socks5|off"
#     fi
#     # check the proxy
#     echo "\nnow:"
#     curl cip.cc
# }

passgen() {
    read -s MSG
    echo -n "$MSG" | openssl dgst -sha256 -binary | base64 | head -c 12 | awk '{print $0"K@!"}'
}
# ---------------- constants ----------------

# some aliases
alias v='nvim'
alias f='fastfetch'
alias py='python3'

# env
export EDITOR='nvim'
export VISUAL='nvim'


# >>> mamba initialize >>>
# !! Contents within this block are managed by 'micromamba shell init' !!
export MAMBA_EXE='/usr/bin/micromamba';
export MAMBA_ROOT_PREFIX='/home/Kalium/.local/share/mamba';
__mamba_setup="$("$MAMBA_EXE" shell hook --shell zsh --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias micromamba="$MAMBA_EXE"  # Fallback on help from micromamba activate
fi
alias conda='micromamba'
unset __mamba_setup
# <<< mamba initialize <<<


# ---------------- misc ----------------

__get_prompt_extra_info() {
    echo $(__get_conda_env)$(__get_nix_shell)
}

__get_nix_shell() {
    if [ -n "$IN_NIX_SHELL" ]; then
        echo "─{:${name}}"
    fi
}

__get_conda_env() {
    CONDA_SYMBOL=":"
    CONDA_ENV=""
    if [ -n "$CONDA_PREFIX" ]; then
        CONDA_DIR=$(basename $CONDA_PREFIX)
        if [ "$CONDA_DIR" == "anaconda" ]; then
            CONDA_ENV="base"
        else
            CONDA_ENV=$CONDA_DIR
        fi
        echo "─{${CONDA_SYMBOL}${CONDA_ENV}}"
    fi
}

# env for xdg dir
# bash
export HISTFILE="$XDG_STATE_HOME"/zsh/history
# gnu readline
export INPUTRC="$XDG_CONFIG_HOME"/readline/inputrc
# android toolchain
export ANDROID_USER_HOME="$XDG_DATA_HOME"/android
alias adb='HOME="$XDG_DATA_HOME"/android adb'
# nv
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
# gnupg
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
# node
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export MODE_REPL_HISTORY="$XDG_STATE_HOME"/node_repl_history
# rust toolchain
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
# dotnet toolchain
export DOTNET_CLI_HOME="$XDG_DATA_HOME"/dotnet
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
# java toolchain
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
# python toolchain
export PYTHON_HISTORY="$XDG_STATE_HOME"/python
