[font]
size = 14.0
# normal = {family = "JetBrainsMonoNF"}

[colors.primary]
foreground = "#D9E0EE"
background = "#191724"

[colors.normal]
black = "#6E6C7E"
#color8 #988BA2
red = "#F28FAD"
#color9 #F28FAD
green = "#ABE9B3"
#color10 #ABE9B3
yellow = "#FAE3B0"
#color11 #FAE3B0
blue = "#96CDFB"
#color12 #96CDFB
magenta = "#F5C2E7"
#color13 #F5C2E7
cyan = "#89DCEB"
#color14 #89DCEB
white = "#D9E0EE"
#color15 #D9E0EE

